version: '3.9'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        environment:
            DB_DRIVER: django.db.backends.postgresql
            DB_NAME: project_db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: db
            DB_PORT: 5432
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: project_db
        ports:
            - '5432:5432'

volumes:
    postgres_data:
